# SPDX-FileCopyrightText: Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-FileCopyrightText: Copyright (c) 2025 Timor Knudsen (AMD)

# SPDX-License-Identifier: MIT

name: Simulation

on: [push]

jobs:
  build:
    name: "Run test bench simulations"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/amd/mini-isp-dev:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Simulation
      run: make sim
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Simulation artifacts
        path: |
          build/sim/**/*.png
          build/sim/**/*.pdf
          build/sim/**/*.xml
        retention-days: 1
