# SPDX-FileCopyrightText: Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-FileCopyrightText: Copyright (c) 2025 Timor Knudsen (AMD)

# SPDX-License-Identifier: MIT

name: Test

on: [push]

jobs:
  build:
    name: "Run Python tests"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/amd/mini-isp-dev:latest
      options: --user root
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Test
      run: make test
